# Generated by Django 5.0 on 2023-12-21 00:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_csssnippet_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='csssnippet',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
