# Generated by Django 5.0 on 2023-12-21 00:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_csssnippet_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csssnippet',
            name='created',
        ),
        migrations.AddField(
            model_name='csssnippet',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 21, 0, 46, 39, 661822, tzinfo=datetime.timezone.utc)),
        ),
    ]
