# Generated by Django 5.0 on 2023-12-21 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_snippet_delete_csssnippet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='code_type',
            new_name='primary_code_type',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='date_added',
        ),
        migrations.AddField(
            model_name='snippet',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='code',
            field=models.TextField(default=''),
        ),
    ]
