# Generated by Django 5.0 on 2023-12-21 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_rename_code_type_snippet_primary_code_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='code',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='description',
            field=models.TextField(default=' '),
        ),
    ]
