# Generated by Django 5.0 on 2023-12-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_snippet_code_alter_snippet_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='code',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='primary_code_type',
        ),
        migrations.AddField(
            model_name='snippet',
            name='css_code',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='snippet',
            name='html_code',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='snippet',
            name='js_code',
            field=models.TextField(default=' '),
        ),
    ]
