# Generated by Django 5.0 on 2023-12-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_remove_snippet_code_remove_snippet_primary_code_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='css_code',
            field=models.TextField(default='/* css */'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='html_code',
            field=models.TextField(default='<!-- html -->'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='js_code',
            field=models.TextField(default='// js'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='title',
            field=models.CharField(default='untitled', max_length=100),
        ),
    ]
