# Generated by Django 5.0 on 2023-12-27 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_snippet_css_code_alter_snippet_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvoted', models.BooleanField(default=True)),
                ('snippet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.snippet')),
            ],
        ),
    ]
