# Generated by Django 5.0 on 2023-12-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_upvote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upvote',
            name='upvoted',
        ),
        migrations.AddField(
            model_name='upvote',
            name='upvote_type',
            field=models.CharField(choices=[('UP', 'Upvote'), ('DOWN', 'Downvote')], default='UP', max_length=4),
        ),
    ]
