# Generated by Django 5.0 on 2023-12-27 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_remove_upvote_upvoted_upvote_upvote_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Upvote',
            new_name='Vote',
        ),
    ]
