# Generated by Django 5.0 on 2023-12-27 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_rename_upvote_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='upvote_type',
            new_name='vote_type',
        ),
    ]
