# Generated by Django 5.0 on 2023-12-27 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_rename_vote_type_vote_v_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='v_type',
            new_name='vote_type',
        ),
    ]
