# Generated by Django 5.0 on 2023-12-27 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_rename_vote_type_vote_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='type',
            new_name='vote_type',
        ),
    ]
