# Generated by Django 5.0 on 2023-12-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='tags',
            field=models.ManyToManyField(to='main_app.tag'),
        ),
    ]
